//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lapushokEntities : DbContext
    {
        private static lapushokEntities _context;
        public static lapushokEntities GetContext()
        {
            if (_context == null) _context = new lapushokEntities();
            return _context;
        }
        public lapushokEntities()
            : base("name=lapushokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Заказ_материалов> Заказ_материалов { get; set; }
        public virtual DbSet<Мастер_производства> Мастер_производства { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<Смены> Смены { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
