//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_материалов
    {
        public int ID_Заказ_материалов { get; set; }
        public Nullable<int> ID_Материалы { get; set; }
        public Nullable<int> ID_Продукция { get; set; }
        public Nullable<int> Необходимое_количество_материала { get; set; }
    
        public virtual Материалы Материалы { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
