//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Заказ_материалов = new HashSet<Заказ_материалов>();
        }
    
        public int ID_Продуцкция { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<int> Минимальная_стоимость_для_агента { get; set; }
        public byte[] Изображение { get; set; }
        public string Тип_продукции { get; set; }
        public Nullable<int> Количество_человек_для_производства { get; set; }
        public Nullable<int> Номер_цеха_для_производства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_материалов> Заказ_материалов { get; set; }
    }
}
