//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int ID_Сотрудника { get; set; }
        public string ФИО { get; set; }
        public System.DateTime Дату_рождения { get; set; }
        public string Паспортные_данные { get; set; }
        public string Банковские_реквезиты { get; set; }
        public int ID_Смены { get; set; }
        public string Семейное_положение { get; set; }
        public string Здоровье { get; set; }
    
        public virtual Смены Смены { get; set; }
    }
}
